package com.fstn;
// Generated by delombok at Thu Oct 15 17:02:51 CEST 2015
/*
 * Copyright (c) 2013 All Rights Reserved, ITESOFT
 */

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * The Class Invoice.
 * <p/>
 * <p/>
 * <p/>
 * <TABLE summary="database mapping">
 * <p/>
 * <TR>
 * <p/>
 * <TD>grpBusinessId</TD>
 * <p/>
 * <TD>GRP_BUSINESS_ID</TD>
 * <p/>
 * </TR>
 * <p/>
 * <TR>
 * <p/>
 * <TD>supplier</TD>
 * <p/>
 * <TD>SUPPLIER_ID</TD>
 * <p/>
 * </TR>
 * <p/>
 * <TR>
 * <p/>
 * <TD>supplier</TD>
 * <p/>
 * <TD>SUPPLIER_ID</TD>
 * <p/>
 * </TR>
 * <p/>
 * </TABLE>
 *
 * @see PaymentDTO
 * @see PaymentGrpDTO
 * @see CompanyDTO
 * @see SupplierDTO
 * @see InvoiceDTO
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Invoice implements Serializable {

    /**
     * Default Constructor
     */
    public Invoice() {
        super();
    }


    @Override
    public String toString() {
        return
                "id : " + this.id
                        + " status : " + this.status
                        + " date : " + this.date
                        + " dueDate : " + this.dueDate
                        + " number : " + this.number
                        + " totalAmount : " + this.totalAmount
                        + " totalNetAmount : " + this.totalNetAmount
                        + " site : " + this.site
                        + " type : " + this.type
                        + " currency : " + this.currency
                        + " code : " + this.code
                        + " scanDate : " + this.scanDate
                        + " batchName : " + this.batchName
                        + " dateChangeState : " + this.dateChangeState
                        + " custom1 : " + this.custom1
                        + " custom2 : " + this.custom2
                        + " custom3 : " + this.custom3
                        + " custom4 : " + this.custom4
                        + " custom5 : " + this.custom5
                        + " showImage : " + this.showImage;

    }

    private static final long serialVersionUID = 1L;

    /**
     * The index.      *
     * id
     */
    private Integer id;

    /**
     * status
     */
    private String status;

    /**
     * The date.      *
     * date
     */
    private Date date;

    /**
     * The date.      *
     * dueDate
     */
    private Date dueDate;

    /**
     * The invoice number.
     * <p/>
     * number
     */
    private String number;

    /**
     * The TTC total amount.      *
     * totalAmount
     */
    private BigDecimal totalAmount;

    /**
     * The net total amount.      *
     * totalNetAmount
     */
    private BigDecimal totalNetAmount;

    /**
     * The site.      *
     * site
     */
    private String site;

    /**
     * The type.
     * <p/>
     * type
     */
    private String type;

    /**
     * The currency.      *
     * currency
     */
    private String currency;

    /**
     * The itesoft id.
     * <p/>
     * code
     */
    private String code;

    /**
     * The scan date.      *
     * scanDate
     */
    private Date scanDate;

    /**
     * The batchname.      *
     * batchName
     */
    private String batchName;

    /**
     * The date change state.      *
     * dateChangeState
     */
    private Date dateChangeState;

    /**
     * The custom1.      *
     * custom1
     */
    private String custom1;

    /**
     * The custom2.      *
     * custom2
     */
    private String custom2;

    /**
     * The custom3.
     * <p/>
     * custom3
     */
    private String custom3;

    /**
     * The custom4.      *
     * custom4
     */
    private Date custom4;

    /**
     * The custom5.      *
     * custom5
     */
    private Date custom5;

    private int supplierId;

    private String supplierName;

    private int companyId;

    private String companyName;

    private boolean showImage;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public BigDecimal getTotalNetAmount() {
        return totalNetAmount;
    }

    public void setTotalNetAmount(BigDecimal totalNetAmount) {
        this.totalNetAmount = totalNetAmount;
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Date getScanDate() {
        return scanDate;
    }

    public void setScanDate(Date scanDate) {
        this.scanDate = scanDate;
    }

    public String getBatchName() {
        return batchName;
    }

    public void setBatchName(String batchName) {
        this.batchName = batchName;
    }

    public Date getDateChangeState() {
        return dateChangeState;
    }

    public void setDateChangeState(Date dateChangeState) {
        this.dateChangeState = dateChangeState;
    }

    public String getCustom1() {
        return custom1;
    }

    public void setCustom1(String custom1) {
        this.custom1 = custom1;
    }

    public String getCustom2() {
        return custom2;
    }

    public void setCustom2(String custom2) {
        this.custom2 = custom2;
    }

    public String getCustom3() {
        return custom3;
    }

    public void setCustom3(String custom3) {
        this.custom3 = custom3;
    }

    public Date getCustom4() {
        return custom4;
    }

    public void setCustom4(Date custom4) {
        this.custom4 = custom4;
    }

    public Date getCustom5() {
        return custom5;
    }

    public void setCustom5(Date custom5) {
        this.custom5 = custom5;
    }

    public int getSupplierId() {
        return supplierId;
    }

    public void setSupplierId(int supplierId) {
        this.supplierId = supplierId;
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public int getCompanyId() {
        return companyId;
    }

    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public boolean isShowImage() {
        return showImage;
    }

    public void setShowImage(boolean showImage) {
        this.showImage = showImage;
    }
}
